src/aggregate.rs

We can avoid the `(s)` by inspecting the number. And using spaces instead of tabs makes the output more consistent in a terminal, no longer depending on the length of the preceding filename.

error formatting suggestions

---

src/interactive/app/handlers.rs
src/interactive/widgets/entries.rs
src/interactive/widgets/footer.rs
src/interactive/widgets/header.rs
src/interactive/widgets/main.rs
src/interactive/widgets/mark.rs
src/interactive/widgets/mod.rs

Fixes #13.
Due to the way colors work in the terminal, I had to change the color scheme for dark terminals as well.
I also tried to make the coloring of the entries and the mark pane more consistent.

Fix color scheme for light terminals

---

Cargo.lock
Cargo.toml
src/aggregate.rs
src/common.rs
src/interactive/app_test/utils.rs
src/main.rs
src/options.rs
src/traverse.rs

This adds support for retrieving the real on-disk size of files using the `filesize` crate, leaving the previous behaviour under `-A`/`--apparent-size` flags to match BSD/GNU `du`.

Add support for real/apparent size

---

README.md
src/aggregate.rs
src/common.rs
src/inodefilter.rs
src/interactive/app_test/utils.rs
src/lib.rs
src/main.rs
src/options.rs
src/traverse.rs

This adds a simple `HashMap`-based inode filter, and `-l` and `--count-links` flags to disable it, again mirroring BSD and GNU `du`.
Windows support needs work since it's using unstable features, but the build appears broken there anyway.

Add hardlink tracking, and an option to disable it

---

README.md

dua-cli is now available out-of-the-box on Arch Linux!
Thanks Sven-Hendrik Haase for adopting the package into the `[community]` repo!

Add ArchLinux to README.md

---

tui-react/Cargo.toml

The only default feature in tui is the termion backend, but tui-react doesn't depend on any backend. With the termion backend enabled by default you can't change the backend to another one in other crates.

Disable default features for tui in tui-react

---

src/inodefilter.rs

Inodes are only unique per device, so include device in the lookup.
Also replace a conditional with an additional pattern match, makes it a
bit tidier I think.

Fix inode filtering with multiple devices

---

src/aggregate.rs
src/common.rs
src/interactive/app_test/utils.rs
src/interactive/widgets/entries.rs
src/interactive/widgets/footer.rs
src/interactive/widgets/mark.rs
src/traverse.rs

Per issue #58, u64 is insufficient for use with very large sparse files.
Enormous file sizes are also a common filesystem error trope, either
from disk corruption or software bugs, and they're also conceivable with
virtual filesystems.
Handle this as gracefully as can be reasonably expected using 128-bit
integers, which should be sufficient for most uses.

Use u128 for byte sizes

---

src/interactive/app_test/unit.rs
src/interactive/app_test/utils.rs

- fixes 'sample_01_tree' size miscalculation; symbolic links are '0' size on windows vs '1' size on *nix-types
- fixes 'sample_02_tree' path construction error
Both tests now complete successfully on Windows and *nix-type platforms.

Fix disabled tests

---

src/interactive/app/eventloop.rs
src/interactive/widgets/help.rs
src/interactive/widgets/mark.rs
src/interactive/widgets/mod.rs
src/main.rs

This changeset replaced colors for entries in interactive mode
directory: from none to cyan
regular file: from dark gray to none
Before:
After:

Fix styling for entries for interactive mode

---

src/aggregate.rs

Use cyan color for folders in aggregate mode
Before:
After:

src, aggregate: fix colors for aggregate mode

---

README.md

Hi, `dua-cli` being available via Homebrew, I just added the corresponding section. Cheers

add installation instructions via homebrew

---

Cargo.toml
Makefile
src/interactive/app/handlers.rs
src/interactive/widgets/help.rs
src/interactive/widgets/mark.rs

On *BSD systems, the [trash](https://github.com/ArturKovacs/trash-rs) crate does not compile successfully in what appears to rely on Linux-specific implementations (`libc::getmntent` to name a few). 
<details>
<summary>Compilation log</summary>
<p>
```
error[E0432]: unresolved import `chrono`
--> /home/lcook/.cargo/registry/src/github.com-1ecc6299db9ec823/trash-2.0.1/src/freedesktop.rs:18:5
|
18 | use chrono::{NaiveDateTime, TimeZone};
|     ^^^^^^ use of undeclared crate or module `chrono`
error[E0432]: unresolved import `scopeguard`
--> /home/lcook/.cargo/registry/src/github.com-1ecc6299db9ec823/trash-2.0.1/src/freedesktop.rs:20:5
|
20 | use scopeguard::defer;
|     ^^^^^^^^^^ use of undeclared crate or module `scopeguard`
error: cannot determine resolution for the macro `defer`
--> …
```

Make the trash feature optional

---

src/interactive/app/eventloop.rs
src/interactive/widgets/entries.rs
src/interactive/widgets/help.rs
src/interactive/widgets/mark.rs

I'm one the people who use arrow keys and page up/down/home/end to navigate instead of alphabet keys 😄 and I find it weird that dua doesn't support Home/End. This is a pretty trivial change, so I hope you will accept it.
I also took the chance to fix inconsistent casing (opinionated), wording and forgotten `help_text` change to `help.rs` in 7689016c537d054a519e4e61c577e30645537213.

Support Home/End and fix inconsistent help text

---

src/interactive/widgets/mark.rs

I find the current style looking a little bit weird, so I tried to improve it a little bit, see comparison below.
Before:
After:

Improve mark widget tip style

---

src/interactive/app/handlers.rs

Rust 1.55 unfortunately breaks the existing code which assumed that
ErrorKind::Other will be returned by fs::read_dir() when a file is
encountered. For now just always try deleting as if it's a file with the
possibility to add the optimization back again once the `io_error_more`
feature is stabilized.
References:
- https://blog.rust-lang.org/2021/09/09/Rust-1.55.0.html#stdioerrorkind-variants-updated
- https://github.com/rust-lang/rust/pull/85746
- https://github.com/rust-lang/rust/issues/86442

Fix deletion process on Rust 1.55

---

src/aggregate.rs

This change would allow dua to be built on platforms without 64-bit atomics.

fix: build on platforms without 64-bit atomics

---

src/interactive/app/eventloop.rs
src/interactive/app/handlers.rs
src/interactive/widgets/help.rs
src/interactive/widgets/mark.rs

Hi, I just found this project, and I think it's great! However, one inconvenience I've found with it is the inability to mark all files in a directory for deletion. I have added <kbd>a</kbd> to fulfill that functionality here.
I extracted the functionality of the `mark_entry` function that uses `index` into a function `mark_entry_by_index` that is then used in the original `mark_entry` function and a new `mark_all_entries` function.
Another thing to mention is that I made <kbd>a</kbd> toggle the marked status of all entries, rather than marking all of them, because I think the former would be slightly more useful in that if you wanted to mark all but select files, you could start by marking those select files, then toggle all.

Add `a` key to toggle marked status of all entries

---

Cargo.toml
Makefile
src/aggregate.rs

Previously, aggregate mode progress reports were handled by an
infinitely-looping thread carrying a 64-bit atomic of the current count,
which it would print periodically.
This resulted in #99 - breaking on platforms without 64-bit atomics,
for which a feature was added to disable it.
It also implied a race condition, where the "Enumerating ..." message
could be printed after results had been gathered but before dua exited.
Additionally, part of the status message could be left on the display if
the first line of a report was too short to cover it.
This commit should resolve these:
* The 64-bit atomic counter is replaced with an 8-bit AtomicBool
* All printing is controlled from the main thread
* The first line is cleared prior to printing a report
The only notable drawback I see with this …

Improve aggregate progress reporting

---

README.md

[`dua`](https://scoop.sh/#/apps?q=main%2Fdua&s=0&d=1&o=true) is available in Scoop for Windows.

Add Scoop installation for Windows

---

src/main.rs

Closes #135 (I really overestimated how complex these changes would be 😅)
Measured 1-8 threads on both a small (100MB) and large (80GB) directories, 4 threads was the most performant in both cases.

Add Apple M2 to default thread derivation

---

Cargo.lock
Cargo.toml
src/aggregate.rs

`owo-colors` is well-maintained, zero-allocation, zero-dependencies crate
for terminal colors. Also it works on any type that implements Display trait,
not just on strings.
I made minimal changes to the source code for this switch.

Dependencies: switch from colored to owo-colors

---

src/interactive/app/eventloop.rs

Fixes #143 (on my machine). It looks like commit 28f5ac90cc1ba7d668ae8a83eb5cd899294a8301 unintentionally removed a call to `draw`. Putting it back in appears to fix the issue. Will definitely need to verify on other people's machines.

Draw window before processing events, fixes #143

---

src/aggregate.rs
src/common.rs
src/traverse.rs

Like it says in the title. Right now, if you pass `-x`, dua doesn't count files on other devices, but it still enumerates them. However, a good reason to use `-x` is if you have network mounts that are slow, so this fixes that.

traverse: don't recurse on cross-device filesystems

---

src/options.rs

use binary format by default (except on macOS)

---

Cargo.lock
Cargo.toml
src/common.rs
src/interactive/app/common.rs
src/interactive/app/eventloop.rs
src/interactive/app/handlers.rs
src/interactive/app/tests/journeys_readonly.rs
src/interactive/app/tests/utils.rs
src/interactive/widgets/entries.rs
src/interactive/widgets/footer.rs
src/interactive/widgets/help.rs
src/interactive/widgets/main.rs
src/traverse.rs

Adds keybinding for 'm' to toggle sorting by modified time. Additionally appropriate column is highlighted depending on if sorting is by time or by size + mtime column is hidden by default.
Sorting by modified time + current sorting mode in the footer:
Help:
Addresses issue #141

Adds keybinding for 'm' to toggle sorting by modified time

---

Cargo.toml

I know this is super low hanging fruit so I am probably missing something, but why was it set to `0`?

Increase optimization level

---

src/main.rs

Implements the suggestion from #110 to skip single root directory.
Before:
After:

Skip through single root directory

---

Cargo.lock
Cargo.toml
src/interactive/app/common.rs
src/interactive/app/eventloop.rs
src/interactive/app/handlers.rs
src/interactive/app/tests/journeys_readonly.rs
src/interactive/app/tests/utils.rs
src/interactive/widgets/entries.rs
src/interactive/widgets/footer.rs
src/interactive/widgets/help.rs
src/traverse.rs

Adds keybinding for 'c' to toggle sorting by number of items. I have used `human_format` to convert numbers to more human readable form.
Number of items in each directory is collected the same way as the size was done before during file system traversal. I have updated the tests to ensure the counts are calculated correctly.
Sorting by number of items + current sorting mode in the footer:

Adds keybinding for 'c' to toggle sorting by number of items

---

Cargo.lock
Cargo.toml
src/interactive/widgets/entries.rs

Displays total item count

---

src/interactive/app/eventloop.rs

I have found previous version with the `Option<>` a bit weird, but it is probably a matter of taste. In the new version AppState is created at the start,  but unfortunately we have to deal with incoming events which complicate things.
However, I am not sure if we need to process the events during the traversal. The app is not that usable in that state anyway - events are all processed in batches which causes the cursor jump around a bit, and the experience is not smooth at all.
Also, as an example `ncdu` doesn't allow any interaction during scanning. Thoughts?

Refactors AppState initialisation during app startup

---

src/interactive/widgets/entries.rs

Adds the missing '/' prefix for root directories

---

Cargo.lock
Cargo.toml
src/interactive/app/common.rs
src/interactive/app/eventloop.rs
src/interactive/app/handlers.rs
src/interactive/app/mod.rs
src/interactive/app/navigation.rs
src/interactive/app/tests/journeys_readonly.rs
src/interactive/app/tests/journeys_with_writes.rs
src/interactive/app/tests/unit.rs
src/interactive/app/tests/utils.rs
src/interactive/app/tree_view.rs
src/interactive/mod.rs
src/interactive/widgets/entries.rs
src/interactive/widgets/glob.rs
src/interactive/widgets/help.rs
src/interactive/widgets/main.rs
src/interactive/widgets/mark.rs
src/interactive/widgets/mod.rs
src/traverse.rs

Implements glob search feature as requested in #154 
There are three main components to in the implementation of this feature:
* `NavigationState`
* there are separate instances for normal and glob modes. This lives inside the `AppState` and holds the state of there the user has been navigating etc.
* Depending in which mode you are you need a different "view" of the tree. This is where new `TreeView` trait comes in. `AppState::process_events` has been refactored to create appropriate tree view (normal vs glob) for the mode you are in and us that to handle the events.
* Doing a glob search adds a new tree root which gets removed when the search is cancelled.
* Glob has its own pane etc. where user input and rendering is handled.
* UI components have been refactored to only need basic …

Implements glob search feature

---

src/aggregate.rs
src/interactive/app/handlers.rs
src/interactive/app/tests/journeys_readonly.rs
src/interactive/app/tests/journeys_with_writes.rs
src/interactive/widgets/footer.rs
src/interactive/widgets/help.rs

Consistent language is important. We have started using "items" in few places and it seems more correct in `dua`'s context: entry is something that has been put in vs an item in a list. I have also made sure all sentences start a with capital letter and end with a dot - it looks more mature / professional. 
Before:
After:

Keep consistent language/punctuation/case throughout the app.

---

Cargo.lock
Cargo.toml
src/common.rs
src/interactive/app/bytevis.rs
src/interactive/app/eventloop.rs
src/interactive/widgets/help.rs
src/main.rs
src/options.rs

I find logs very useful. So far I had to keep applying this patch on top of my changes. It would be useful to add this option to the cli to help with debugging. I hope the logs will improve in the future to include more interesting info abouy the operation of the program.

Option to enable debug logs

---

Cargo.lock
Cargo.toml
src/interactive/app/eventloop.rs
src/interactive/app/input.rs
src/interactive/app/mod.rs
src/traverse.rs

The UI is very laggy while the scanning is in progress, and it makes the program almost unusable during the first few seconds of startup. The bottleneck is `jwalk` iterator, it may block the UI thread sometimes. In this PR, I alleviated the situation by some optimizations, and the UI is now super responsive at startup.
Here is what it looks like:
https://github.com/Byron/dua-cli/assets/3109144/3b06b888-c4ec-4c45-9468-36b0059cbe6c
Some implementation notes:
- The traversal operation is moved to another thread to prevent the UI thread from being blocked, and its results are sent to the UI thread via a channel.
- Use `crossbeam::channel` to receive UI events and `jwalk` entries. In contract to `std::sync::mpsc`, we can select from a set of channels without busy polling using `try_recv`.
- …

Optimize UI responsiveness in scanning state

---

src/interactive/app/eventloop.rs
src/interactive/app/handlers.rs
src/interactive/app/state.rs
src/interactive/widgets/entries.rs
src/interactive/widgets/help.rs
src/interactive/widgets/main.rs

feat: show and hide mtime and item count columns with 'M' and 'C' respectively

---

src/interactive/app/common.rs
src/interactive/app/eventloop.rs
src/interactive/app/handlers.rs
src/interactive/app/terminal.rs
src/interactive/app/tree_view.rs

Related to #223
Previously each time the UI refreshes, every 250ms, it display
entries but also check their metadata to assure they exist.
This could lead to performance loss when the displayed folder
has a lot of entries.

fix overhead

---

src/interactive/app/common.rs
src/interactive/app/eventloop.rs
src/interactive/app/handlers.rs
src/interactive/app/state.rs
src/interactive/app/terminal.rs
src/interactive/app/tests/utils.rs
src/interactive/app/tree_view.rs
src/main.rs
src/options.rs

With it, in interactive mode, entries will not be checked for presence.
This can avoid laggy behaviour when switching between directories
as `lstat` calls will not run, which can be slow on some filesystems.
Fixes #227

add --no-entry-check flag

---

.github/workflows/release.yml

Hello! Looking at https://github.com/Byron/dua-cli/issues/68 I see this was requested/fulfilled previously, though it seems releases have only ever been for `arm`, which is 32bit architecture specifically.
This PR adds aarch64/arm64 build support, using https://github.com/rust-cross/rust-musl-cross - I'm not overly familiar with rust and friends, so this may not be desired. Does seem to work as expected though (tested on the arm64 machine I'm wanting to use) - you can see/test results here: https://github.com/chessmango-forks/dua-cli/releases/tag/v2.28.3

feat: arm64 builds

---

src/interactive/widgets/entries.rs

This PR adds a scrollbar for the main list to better indicate the current position of the viewport. See it in action:
https://github.com/Byron/dua-cli/assets/3109144/88cea506-fa29-4d80-95ad-be4b0e79740c

Add scrollbar for main list

---

Cargo.lock
Cargo.toml
src/interactive/widgets/mark.rs

As discussed in #233, this PR also adds a scrollbar for the mark panel.

Add scrollbar for mark list

---

README.md

All other similar tools had links, except Filelight. Well, not anymore!

Added link to Filelight

---

.github/workflows/release.yml

- This pull request modifies YAML configurations of GitHub Workflows.
- This introduce a new job `winget-release` in `.github\workflows\release.yml`.
- It runs after job `build-release`.
- After all production assets are uploaded to GitHub Releases, another pull request will be created by [WinGet Releaser](https://github.com/marketplace/actions/winget-releaser)
- The action will create YAML manifests of the new release by using [Komac](https://github.com/russellbanks/Komac), just like what human contributors do.
- Currently, 2 assets (matching regex `pc-windows-msvc.zip$`) will be included in the manifest.
- Resolve #255 
> [!IMPORTANT]
>
> In order to run properly, this job requires:
>
> 1. Create a **classic** PAT with `public_repo` permissions granted, and add it to a repository secret …

Feature: Auto submit new manifest to winget-pkgs

---

README.md

Hi, I've added instructions on how to install dua using x-cmd to the README file.
- [x-cmd](https://www.x-cmd.com/) is a **toolbox for Posix Shell**, offering a lightweight package manager built using shell and awk.
```sh
x env use dua
```

README.md: add x-cmd install steps

---

.github/workflows/release.yml

The release workflow failed because actions/upload-artifact@v1 doesn't work anymore.
https://github.com/Byron/dua-cli/actions/runs/11649383977/job/32436848048
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v1`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
```
https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
Due to this error, no asset was released at v2.29.3.
https://github.com/Byron/dua-cli/releases/tag/v2.29.3

ci: fix the failure of the release workflow by updating actions/upload-artifact to v4

---

src/interactive/app/handlers.rs
src/interactive/app/tests/journeys_readonly.rs
src/interactive/app/tests/utils.rs
src/interactive/widgets/entries.rs
src/interactive/widgets/help.rs
src/main.rs

style: simplify some statements for readability

---

src/interactive/app/common.rs
src/interactive/app/eventloop.rs
src/interactive/app/handlers.rs
src/interactive/app/tests/journeys_readonly.rs
src/interactive/widgets/footer.rs
src/interactive/widgets/glob.rs
src/interactive/widgets/help.rs
src/traverse.rs

Hi! This PR closes #269 by allowing users to toggle ascending / descending sort by name using the 'n' hotkey. A couple of notes on the design here, illustrated in the screen recording below.
- When the sort is first toggled, it is ascending by default, unlike the other sort modes, which default to descending (presumably users want to sort A-Z rather than Z-A)
- Entries are sorted first by type (directories before files) and lexicographically by name within each type. My thinking here is that users are likely sorting alphabetically so that they can navigate more easily. This is in line with how other command line tools like vim's file explorer perform sort by name.
- Names are sorted lexicographically rather than with a [natural sort](https://en.wikipedia.org/wiki/Natural_sort_order) as …

Feature: allow sorting by dirname / filename in interactive mode

---

src/aggregate.rs
src/interactive/app/tests/utils.rs
src/traverse.rs

Hi! This closes #262 where directory inode sizes are mistakenly being excluded from total disk usage calculations. This PR brings the behaviour of `dua` in line with that of `du` in both aggregate (`f44e19d`) and interactive (`ef1833a`) modes.
For example, given a directory tree structured as followed
```
/test_dir/
├── file1.txt (1KB)
├── empty_dir/
└── populated_dir/
└── file2.txt (2KB)
```
dua currently outputs
With these changes:
Some notes on the changes made:
- In aggregate mode it suffices simply to remove the `!m.is_dir()` condition when traversing, as directory metadata can be handled just the same as non-directory file metadata
- In interactive mode, the changes are slightly more complex due to how entry size is recursively computed. We have existing logic for computing the size …

Fix: Directories themselves do not contribute to size like they do in du

---

Cargo.lock
Cargo.toml
src/aggregate.rs
src/interactive/widgets/mark.rs
src/main.rs
src/options.rs

Hey there, love your work on dua!
I've just added the ability to generate shell completions for common shells. If you also want Nushell support, an additional dependency and some additional code will be required. Please let me know. 😄 
Cheers
Fotis

Add the ability to generate shell completions
